### ISSUE TITLE
vercelにbasic認証をかける

### ISSUE THREAD

**Issue by underground0930** [yassun-youtube/the-hack-2022-nov-team-3#7]
## 対応すること
サイトにbasic認証をかける
https://blog.kimizuka.org/entry/2021/06/09/231526
https://github.com/yassun-youtube/the-hack-2022-nov-team-4/blob/add_basic_auth/middleware.ts

**Comment by wanpa** [comment]
@underground0930 
おつかれさまです！
4班のを真似てベーシック認証を入れてみたのですが
middleware.tsの配置の違いがありまして

・4班はルート直下
・3班はsrc直下
https://github.com/yassun-youtube/the-hack-2022-nov-team-3/tree/feature/vercel_basic_auth

にしていまして
ルート直下だとmiddlewareが着火しない感じでした。？
どこかで決めるところあるんですかね。

一応、ベーシック認証はsrc配下に入れると動くのですが
何度も聞いてくるんですよ。。

**Comment by wanpa** [comment]
あ、matcherっていうのを入れたら大丈夫でした。
export const config = {
  matcher: ['/'],
}
